name: Repositories
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update repos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          max_post_count: "4"
          repo_list: "https://github.com/jara155?tab=repositories"
